### ISSUE TITLE
ModuleNotFoundError: No module named 'Cryptodome'

### ISSUE THREAD

**Issue by shreyas-badiger** [DP-3T/reference_implementation#1]
Unable to run example_run.py

<img width="1077" alt="Screenshot 2020-04-10 at 11 56 31 AM" src="https://user-images.githubusercontent.com/7680410/79015890-93fa9980-7b22-11ea-86c7-878cc911f236.png">

**Comment by gannimo** [comment]
You need to install the `Cryptodome` library. You can do so through `sudo apt install python3-pycryptodome`, `pip install pycryptodome` or `pip3 install pycryptodomex`. I've updated the README accordingly. Thanks!

**Comment by shreyas-badiger** [comment]
Thanks!
The command is actually:
`pip3 install pycryptodomex`

**Comment by gannimo** [comment]
This depends on your local system. If you have both legacy python and python3 installed then pip installs for legacy, otherwise pip installs for python3. I'll make a note :)

**Comment by avandeursen** [comment]
I think @hard-fault is referring not just to python3, but also to the `x` version of PyCryptodome.

`pip install pycrotodomex` works like a charm for me
`pip install pycrotodome` gives the `ModuleNotFoundError`

**Comment by gannimo** [comment]
OK, I'll adjust. There are too many sub libraries and the different `pip` commands refer to different subsets of the library. Debian/Ubuntu conveniently installs both. Thanks!

**Comment by koenvervloesem** [comment]
Note that in a Python 3 virtual environment, you also [need to install pycryptodomex](https://twitter.com/koenvervloesem/status/1248895790925447168) instead of pycryptodome:

$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip3 install pycryptodome
(venv) $ python3 example_run.py
Traceback (most recent call last):
  File "example_run.py", line 23, in <module>
    import LowCostDP3T
  File "/home/koan/reference_implementation/LowCostDP3T.py", line 20, in <module>
    from Cryptodome.Util import Counter
ModuleNotFoundError: No module named 'Cryptodome'
(venv) $ pip3 install pycryptodomex
(venv) $ python3 example_run.py
Day: Alice, Bob, and Isidor do not have contact.
Day: Alice, Bob, and Isidor do not have contact.
Day: Alice and Bob work in the same office, Isidor elsewhere.
Day: Alice and Bob work in the same office, Isidor elsewhere.
Day: Alice and Bob work in the same office, Isidor elsewhere.
Day: Bob and Isidor meet for dinner.
Isidor is tested positive.
Check exposure of Alice and Bob.
Alice: (not positive)
Bob: (at risk)
At risk, observed e91393fcf6d314d95ad607a1cbe00fa6 on day -1 for 121

**Comment by robin-shaun** [comment]
> I think @hard-fault is referring not just to python3, but also to the `x` version of PyCryptodome.
> 
> `pip install pycrotodomex` works like a charm for me
> `pip install pycrotodome` gives the `ModuleNotFoundError`

A spelling mistake, it's pycryptodomex.

**Comment by 89z** [comment]
@gannimo can you please remove your original comment suggesting `pip install pycryptodome`? Its not longer valid (if it ever was), and that comment shows prominently on a Google search

**Comment by gannimo** [comment]
Updated the comment to give options. Note that the README itself has much changed over time and this thread is likely no longer valid at all for this implementation.

**Comment by 89z** [comment]
@gannimo the Readme is a great reference, but I regardless many people might end up on this page from an internet search (like I did). In this case, I think the comment should be accurate, if the person who made it is still active on GitHub (you are). Unfortunately, I think even with the edit the comment is still misleading, as commands such as `pip install pycryptodome` don't work at all in current Python environments, in regards to fixing the error in the title.
